# Generated by Django 2.0.7 on 2020-02-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeedback',
            name='username',
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='name',
            field=models.CharField(default='Ekko User', max_length=30),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='rating',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='review',
            field=models.TextField(default='Quality Service and Friendly Staff, Must try!'),
        ),
    ]
