# Generated by Django 2.0.7 on 2020-02-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20200204_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='picture_tag',
            field=models.CharField(choices=[('Exterior', 'Ext'), ('Interior', 'Int'), ('Other', 'Oth')], default='Exterior', max_length=1),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
