# Generated by Django 2.0.7 on 2020-02-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20200204_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='picture_tag',
            field=models.CharField(choices=[('Exterior', 'Exterior'), ('Interior', 'Interior'), ('Other', 'Other')], default='Exterior', max_length=1),
        ),
    ]
