# Generated by Django 2.0.7 on 2020-02-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20200204_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='picture_tag',
            field=models.CharField(choices=[('exterior', 'exterior'), ('interior', 'interior'), ('others', 'others')], default='Exterior', max_length=1),
        ),
    ]
