# Generated by Django 2.0.7 on 2020-02-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_auto_20200204_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='picture_tag',
            field=models.CharField(choices=[('exterior', 'exterior'), ('interior', 'interior'), ('others', 'others')], default='exterior', max_length=9),
        ),
    ]
