# Generated by Django 2.0.7 on 2020-01-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20200124_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_booking',
            name='addons',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user_booking',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user_booking',
            name='alternate_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='user_booking',
            name='booking_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user_booking',
            name='car_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user_booking',
            name='coupon_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user_booking',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user_booking',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user_booking',
            name='landmark',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user_booking',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user_booking',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_booking',
            name='pincode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_booking',
            name='prefered_time',
            field=models.TimeField(),
        ),
    ]
