# Generated by Django 2.0.7 on 2020-01-25 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_auto_20200125_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_booking',
            name='package_type',
        ),
    ]
