# Generated by Django 2.0.7 on 2020-01-25 08:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_remove_user_booking_package_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_booking',
            name='package_type',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
