# Generated by Django 2.0.7 on 2020-01-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20200123_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_booking',
            name='addons',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user_booking',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user_booking',
            name='alternate_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='user_booking',
            name='booking_date',
            field=models.DateField(default='1222-22-22'),
        ),
        migrations.AlterField(
            model_name='user_booking',
            name='car_type',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user_booking',
            name='coupon_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='user_booking',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user_booking',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='user_booking',
            name='landmark',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user_booking',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='user_booking',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_booking',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_booking',
            name='prefered_time',
            field=models.TimeField(default='00:00'),
        ),
    ]
