# Generated by Django 2.0.7 on 2020-01-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20200124_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_booking',
            name='package_type',
            field=models.TimeField(default=''),
            preserve_default=False,
        ),
    ]
