# Generated by Django 2.0.7 on 2020-01-25 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_user_booking_package_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_booking',
            name='package_type',
        ),
    ]
