# Generated by Django 2.0.7 on 2020-02-03 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_registereduser_confirm_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisteredUser',
        ),
    ]
