# Generated by Django 2.0.7 on 2020-02-03 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_delete_registereduser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Booking',
            new_name='UserBooking',
        ),
    ]
