# Generated by Django 2.0.7 on 2020-02-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
                ('picture', models.ImageField(upload_to='gallery/')),
            ],
        ),
    ]
