# Generated by Django 2.0.7 on 2020-02-03 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekkoUsers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='confirm_password',
        ),
    ]
