# Generated by Django 2.0.7 on 2020-02-05 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('querys', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='ContactQuery',
        ),
    ]
