# Generated by Django 2.0.7 on 2020-02-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querys', '0002_auto_20200205_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactquery',
            name='phone',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
